/**
 * hourlySummary.model.js
 * Stores hourly order summaries generated by the cron job.
 */

const mongoose = require('mongoose');

const hourlySummarySchema = new mongoose.Schema({
  total_orders: {
    type: Number,
    required: true
  },
  total_amount: {
    type: Number,
    required: true
  },
  timestamp: {
    type: Date,
    required: true
  }
}, { timestamps: true });

module.exports = mongoose.model('HourlySummary', hourlySummarySchema);
